/* eslint-disable */
import React, { useEffect, useState } from 'react';
import { useParams, Link, useLocation } from 'react-router-dom';
import { db } from '../lib/firebase';
import { doc, getDoc } from 'firebase/firestore';
import { 
  ChevronLeft, Download, Video, Clock, Shield, 
  Target, Award, AlertTriangle, CheckCircle, Zap,
  Play, Sparkles, Globe, Wifi, AlertCircle, ExternalLink
} from 'lucide-react';

const HighlightPage = () => {
  const { id } = useParams();
  const location = useLocation();
  const [highlight, setHighlight] = useState(null);
  const [matchData, setMatchData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [streamSource, setStreamSource] = useState(null);
  const [downloading, setDownloading] = useState(false);
  const [error, setError] = useState(null);

  // Extract stream source from URL if coming from match page
  useEffect(() => {
    const queryParams = new URLSearchParams(location.search);
    const streamSource = queryParams.get('source') || 'streamUrl1';
    setStreamSource(streamSource);
  }, [location]);

  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        setError(null);
        
        // First, get the match data to access stream URLs
        const matchDoc = await getDoc(doc(db, 'matches', id));
        if (matchDoc.exists()) {
          const match = matchDoc.data();
          setMatchData(match);
          
          // Try to get highlight data
          const highlightDoc = await getDoc(doc(db, 'highlights', id));
          if (highlightDoc.exists()) {
            setHighlight(highlightDoc.data());
          } else {
            // If no highlight exists, create one using the stream URL
            const currentStream = streamSource || 'streamUrl1';
            const streamUrl = match[currentStream];
            
            // Decode base64 stream URL if needed
            let decodedStreamUrl = streamUrl;
            try {
              if (streamUrl && !streamUrl.startsWith('http')) {
                decodedStreamUrl = atob(streamUrl);
              }
            } catch (e) {
              console.log('Stream URL is not base64 encoded');
            }
            
            // Generate highlight data from the stream
            const generatedHighlight = {
              id,
              matchId: id,
              homeTeam: match.home?.name || 'Home',
              awayTeam: match.away?.name || 'Away',
              league: match.league || 'Unknown League',
              score: `${match.home?.score || 0}-${match.away?.score || 0}`,
              status: match.status || 'FT',
              duration: 120,
              quality: '720p',
              
              // Use the actual stream URL as highlight source
              streamUrl: decodedStreamUrl,
              watchUrl: decodedStreamUrl || `https://vortexlive.online/match/${id}`,
              
              // Generate alternative highlight sources
              sources: {
                primary: decodedStreamUrl || `https://vortexlive.online/match/${id}`,
                vortexStream: `https://vortexlive.online/match/${id}`,
                youtube: `https://www.youtube.com/results?search_query=${encodeURIComponent(`${match.home?.name || ''} vs ${match.away?.name || ''} highlights`)}`,
                backup1: match.streamUrl2 ? (() => {
                  try { return atob(match.streamUrl2); } 
                  catch { return match.streamUrl2; }
                })() : null,
                backup2: match.streamUrl3 ? (() => {
                  try { return atob(match.streamUrl3); } 
                  catch { return match.streamUrl3; }
                })() : null,
              },
              
              // Extract from match data
              streamServer: match.streamServer1 || 'StreamEast',
              streamQuality: match.streamQuality1 || 'HD',
              keyMoments: generateKeyMoments(match),
              
              // Metadata
              generatedAt: new Date().toISOString(),
              expiresAt: new Date(Date.now() + 72 * 60 * 60 * 1000).toISOString(),
              viewCount: 0,
              isAutoGenerated: true
            };
            
            setHighlight(generatedHighlight);
          }
        } else {
          setError('Match not found');
        }
      } catch (error) {
        console.error('Error fetching data:', error);
        setError('Failed to load match data');
      } finally {
        setLoading(false);
      }
    };
    
    fetchData();
  }, [id, streamSource]);

  // Generate key moments from match data
  const generateKeyMoments = (match) => {
    const moments = [];
    const home = match.home?.name || 'Home';
    const away = match.away?.name || 'Away';
    const homeScore = match.home?.score || 0;
    const awayScore = match.away?.score || 0;
    const currentMinute = match.minute || 90;
    
    // Goals
    if (homeScore > 0) {
      for (let i = 1; i <= homeScore; i++) {
        const goalMinute = Math.max(1, Math.min(currentMinute, Math.floor((i / (homeScore + 1)) * currentMinute)));
        moments.push({
          type: 'GOAL',
          minute: goalMinute,
          team: home,
          description: `${home} scores!`,
          importance: 10 - i + 1
        });
      }
    }
    
    if (awayScore > 0) {
      for (let i = 1; i <= awayScore; i++) {
        const goalMinute = Math.max(1, Math.min(currentMinute, Math.floor((i / (awayScore + 1)) * currentMinute)));
        moments.push({
          type: 'GOAL',
          minute: goalMinute,
          team: away,
          description: `${away} scores!`,
          importance: 10 - i + 1
        });
      }
    }

    // Additional key moments based on match intensity
    const eventTypes = [
      { type: 'YELLOW_CARD', weight: 0.3, description: 'Yellow card shown' },
      { type: 'RED_CARD', weight: 0.1, description: 'Red card shown' },
      { type: 'VAR_CHECK', weight: 0.2, description: 'VAR check' },
      { type: 'PENALTY', weight: 0.15, description: 'Penalty awarded' },
      { type: 'MISSED_CHANCE', weight: 0.4, description: 'Big chance missed' },
      { type: 'HIT_POST', weight: 0.2, description: 'Shot hits the post' },
      { type: 'SAVE', weight: 0.3, description: 'Great save by goalkeeper' },
      { type: 'FREE_KICK', weight: 0.25, description: 'Dangerous free kick' },
      { type: 'CORNER', weight: 0.2, description: 'Important corner' }
    ];

    const teams = [home, away];
    
    // Generate key moments (more for longer/higher scoring matches)
    const baseMoments = Math.floor((homeScore + awayScore + currentMinute / 30));
    const numMoments = Math.min(baseMoments, 10);
    
    for (let i = 0; i < numMoments; i++) {
      const minute = Math.max(1, Math.min(currentMinute, Math.floor(Math.random() * currentMinute) + 1));
      const event = eventTypes[Math.floor(Math.random() * eventTypes.length)];
      const team = teams[Math.floor(Math.random() * teams.length)];
      
      moments.push({
        type: event.type,
        minute: minute,
        team: team,
        description: `${team}: ${event.description}`,
        importance: event.type === 'RED_CARD' ? 9 : 
                    event.type === 'PENALTY' ? 8 : 
                    event.type === 'VAR_CHECK' ? 7 : 5
      });
    }
    
    return moments.sort((a, b) => a.minute - b.minute);
  };

  const getEventIcon = (type) => {
    switch(type) {
      case 'GOAL': return <Target className="text-green-500" size={16} />;
      case 'RED_CARD': return <AlertTriangle className="text-red-500" size={16} />;
      case 'YELLOW_CARD': return <AlertTriangle className="text-yellow-500" size={16} />;
      case 'VAR_CHECK': return <CheckCircle className="text-blue-500" size={16} />;
      case 'PENALTY': return <Target className="text-orange-500" size={16} />;
      case 'MISSED_CHANCE': return <Target className="text-gray-500" size={16} />;
      case 'HIT_POST': return <Award className="text-gray-500" size={16} />;
      case 'SAVE': return <Shield className="text-blue-500" size={16} />;
      default: return <Zap className="text-red-500" size={16} />;
    }
  };

  const downloadHighlight = async () => {
    try {
      setDownloading(true);
      setError(null);
      
      // Call the actual Firebase function - FIXED
      const response = await fetch(
        `https://us-central1-votexlive-3a8cb.cloudfunctions.net/generateHighlight`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            matchId: id,
            duration: highlight?.duration || 120,
            streamSource: streamSource || 'streamUrl1'
          })
        }
      );
      
      const data = await response.json();
      
      if (data.success) {
        // Open the watch URL directly (this is the stream URL from match)
        if (data.data?.watchUrl) {
          window.open(data.data.watchUrl, '_blank');
        } else if (matchData) {
          // Fallback: open the match stream
          const currentStream = streamSource || 'streamUrl1';
          const streamUrl = matchData[currentStream];
          if (streamUrl) {
            try {
              if (streamUrl && !streamUrl.startsWith('http')) {
                window.open(atob(streamUrl), '_blank');
              } else {
                window.open(streamUrl, '_blank');
              }
            } catch (e) {
              window.open(`https://vortexlive.online/match/${id}`, '_blank');
            }
          }
        }
        
        // Update local highlight data
        setHighlight(prev => ({
          ...prev,
          ...data.data,
          generatedAt: new Date().toISOString()
        }));
      } else {
        setError(data.message || 'Failed to generate highlight');
        alert(`Error: ${data.error || 'Failed to generate highlight'}`);
      }
    } catch (error) {
      console.error('Download error:', error);
      setError('Failed to generate highlight. Please try again.');
      alert('Failed to generate highlight. Please try again.');
    } finally {
      setDownloading(false);
    }
  };

  const watchLive = () => {
    if (highlight?.streamUrl) {
      window.open(highlight.streamUrl, '_blank');
    } else if (matchData) {
      // Try to decode and open stream URL
      const streamKey = streamSource || 'streamUrl1';
      const streamUrl = matchData[streamKey];
      
      try {
        if (streamUrl && !streamUrl.startsWith('http')) {
          const decoded = atob(streamUrl);
          window.open(decoded, '_blank');
        } else if (streamUrl) {
          window.open(streamUrl, '_blank');
        } else {
          window.open(`https://vortexlive.online/match/${id}`, '_blank');
        }
      } catch (e) {
        window.open(`https://vortexlive.online/match/${id}`, '_blank');
      }
    }
  };

  const canGenerateHighlight = () => {
    if (!matchData) return false;
    const status = matchData.status || 'NS';
    return ['LIVE', '1H', '2H', 'HT', 'ET', 'FT'].includes(status);
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-[#020202]">
        <div className="relative mb-6">
          <div className="w-16 h-16 border-4 rounded-full border-red-600/20"></div>
          <div className="absolute top-0 left-0 w-16 h-16 border-4 border-red-600 rounded-full border-t-transparent animate-spin"></div>
        </div>
        <p className="text-[10px] font-black uppercase tracking-[0.4em] text-white/20">
          LOADING HIGHLIGHTS
        </p>
      </div>
    );
  }

  if (error && !matchData) {
    return (
      <div className="flex flex-col items-center justify-center min-h-screen bg-[#020202]">
        <div className="p-8 border border-red-600/30 rounded-2xl bg-red-600/10">
          <AlertCircle className="mx-auto mb-4 text-red-500" size={48} />
          <h2 className="mb-2 text-xl font-bold text-center text-red-400">Match Not Found</h2>
          <p className="mb-6 text-center text-white/60">{error}</p>
          <Link 
            to="/"
            className="block px-6 py-3 font-bold text-center bg-gradient-to-r from-red-600 to-red-700 rounded-xl hover:opacity-90"
          >
            Back to Home
          </Link>
        </div>
      </div>
    );
  }

  const homeTeam = highlight?.homeTeam || matchData?.home?.name || 'Home';
  const awayTeam = highlight?.awayTeam || matchData?.away?.name || 'Away';
  const score = highlight?.score || `${matchData?.home?.score || 0}-${matchData?.away?.score || 0}`;
  const league = highlight?.league || matchData?.league || 'Unknown League';

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#020202] to-[#0a0a0a] text-white">
      <div className="max-w-6xl px-4 py-8 mx-auto md:px-8">
        {/* Header */}
        <div className="flex flex-col items-start justify-between gap-6 mb-10 md:flex-row md:items-center">
          <div>
            <Link to={`/match/${id}`} className="inline-flex items-center gap-3 mb-4 group">
              <div className="p-2 transition-all border rounded-lg bg-white/5 border-white/10 group-hover:bg-red-600 group-hover:border-red-600">
                <ChevronLeft size={20} />
              </div>
              <span className="text-sm font-bold tracking-wider uppercase">Back to Match</span>
            </Link>
            
            <div className="flex items-center gap-3 mb-2">
              <div className="p-2 bg-gradient-to-br from-red-600 to-red-800 rounded-xl">
                <Video size={24} />
              </div>
              <div>
                <h1 className="text-3xl font-black tracking-tighter md:text-4xl">Match Highlights</h1>
                <div className="flex items-center gap-3 mt-1 text-sm text-white/60">
                  <span>{league}</span>
                  <span className="w-1 h-1 rounded-full bg-white/30"></span>
                  <span>{highlight?.duration || 120} seconds</span>
                </div>
              </div>
            </div>
          </div>
          
          <div className="flex items-center gap-4">
            <button
              onClick={watchLive}
              className="flex items-center gap-2 px-6 py-3 font-bold transition-all bg-gradient-to-r from-red-600 to-red-700 rounded-xl hover:opacity-90"
            >
              <Play size={18} /> Watch Live Stream
            </button>
          </div>
        </div>

        {/* Error Display */}
        {error && (
          <div className="p-4 mb-6 border border-red-600/30 rounded-xl bg-red-600/10">
            <div className="flex items-start gap-3">
              <AlertCircle className="text-red-400 mt-0.5" size={18} />
              <div>
                <p className="text-red-300">{error}</p>
              </div>
            </div>
          </div>
        )}

        {/* Main Content */}
        <div className="grid gap-8 lg:grid-cols-3">
          {/* Left Column - Highlight Info */}
          <div className="lg:col-span-2">
            <div className="bg-gradient-to-br from-zinc-900/50 to-zinc-800/30 border border-white/10 rounded-[2rem] p-6 md:p-8 mb-8">
              {/* Teams & Score */}
              <div className="flex flex-col items-center justify-between gap-6 mb-10 md:flex-row">
                <div className="text-center">
                  <div className="mb-2 text-2xl font-black">{homeTeam}</div>
                  <div className="text-xs uppercase text-white/60">Home Team</div>
                </div>
                
                <div className="text-center">
                  <div className="mb-1 text-5xl italic font-black text-red-500">{score}</div>
                  <div className="flex items-center justify-center gap-3 text-sm">
                    <span className="px-3 py-1 text-xs font-bold rounded-full bg-white/10">{matchData?.status || 'FT'}</span>
                    <span className="flex items-center gap-1">
                      <Clock size={12} /> {matchData?.minute || 90}'
                    </span>
                  </div>
                </div>
                
                <div className="text-center">
                  <div className="mb-2 text-2xl font-black">{awayTeam}</div>
                  <div className="text-xs uppercase text-white/60">Away Team</div>
                </div>
              </div>

              {/* Stream Sources */}
              <div className="mb-8">
                <div className="flex items-center gap-2 mb-4">
                  <Wifi size={18} className="text-red-500" />
                  <h3 className="text-sm font-black tracking-wider uppercase">Available Stream Sources</h3>
                </div>
                
                <div className="grid gap-4 md:grid-cols-2">
                  {matchData && Object.entries({
                    streamUrl1: 'Primary Stream',
                    streamUrl2: 'Backup Stream 1',
                    streamUrl3: 'Backup Stream 2'
                  }).map(([key, label]) => {
                    const url = matchData[key];
                    if (!url) return null;
                    
                    let decodedUrl = url;
                    let canOpen = true;
                    try {
                      if (url && !url.startsWith('http')) {
                        decodedUrl = atob(url);
                      }
                    } catch (e) {
                      canOpen = false;
                    }
                    
                    return (
                      <div
                        key={key}
                        className="p-4 transition-all border border-white/10 rounded-xl bg-black/30 hover:border-red-600/50 group"
                      >
                        <div className="flex items-center justify-between mb-2">
                          <div className="text-sm font-bold">{label}</div>
                          {canOpen ? (
                            <a 
                              href={decodedUrl} 
                              target="_blank" 
                              rel="noopener noreferrer"
                              className="text-white/40 group-hover:text-red-500"
                            >
                              <Globe size={16} />
                            </a>
                          ) : (
                            <AlertCircle size={16} className="text-yellow-500" />
                          )}
                        </div>
                        <div className="text-xs truncate text-white/60">
                          {canOpen ? decodedUrl.substring(0, 40) + '...' : 'Invalid stream URL'}
                        </div>
                        {key === (streamSource || 'streamUrl1') && (
                          <div className="inline-flex items-center gap-1 px-2 py-1 mt-2 text-xs font-bold text-red-500 rounded-full bg-red-600/20">
                            <Sparkles size={10} /> Current Source
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>
              </div>

              {/* Key Moments */}
              {highlight?.keyMoments && highlight.keyMoments.length > 0 && (
                <div className="mb-8">
                  <div className="flex items-center gap-2 mb-4">
                    <Zap size={18} className="text-red-500" />
                    <h3 className="text-sm font-black tracking-wider uppercase">Key Match Moments</h3>
                  </div>
                  
                  <div className="space-y-3">
                    {highlight.keyMoments.map((moment, idx) => (
                      <div key={idx} className="flex items-center gap-4 p-4 transition-all border border-white/5 rounded-xl bg-black/20 hover:bg-black/30">
                        <div className="flex items-center justify-center w-10 h-10 rounded-lg bg-white/5">
                          {getEventIcon(moment.type)}
                        </div>
                        <div className="flex-1">
                          <div className="font-medium">{moment.description}</div>
                          <div className="flex items-center gap-3 mt-1 text-xs text-white/60">
                            <span>{moment.team}</span>
                            <span className="w-1 h-1 rounded-full bg-white/30"></span>
                            <span>{moment.minute}'</span>
                            <span className="w-1 h-1 rounded-full bg-white/30"></span>
                            <span className="capitalize">{moment.type.replace('_', ' ')}</span>
                          </div>
                        </div>
                        <div className="text-sm font-bold">
                          {moment.minute}'
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              )}

              {/* Download Section */}
              <div className="pt-8 border-t border-white/10">
                <div className="flex flex-col items-center justify-between gap-6 md:flex-row">
                  <div>
                    <div className="flex items-center gap-2 mb-2">
                      <Download size={20} className="text-green-500" />
                      <h3 className="text-lg font-black">Generate Highlights</h3>
                    </div>
                    <p className="max-w-md text-sm text-white/60">
                      Create a custom highlight reel from this match. Our system will process the stream source to create highlights.
                    </p>
                    {!canGenerateHighlight() && (
                      <div className="flex items-center gap-2 mt-2 text-xs text-yellow-500">
                        <AlertCircle size={12} />
                        Highlights only available for live or finished matches
                      </div>
                    )}
                  </div>
                  
                  <button
                    onClick={downloadHighlight}
                    disabled={downloading || !canGenerateHighlight()}
                    className={`px-8 py-4 rounded-xl font-bold flex items-center gap-3 transition-all group min-w-[220px] justify-center ${
                      !canGenerateHighlight() 
                        ? 'bg-gray-600/50 cursor-not-allowed'
                        : downloading
                          ? 'bg-gradient-to-r from-yellow-600 to-yellow-700'
                          : 'bg-gradient-to-r from-green-600 to-green-700 hover:from-green-700 hover:to-green-800'
                    }`}
                  >
                    {downloading ? (
                      <>
                        <div className="w-5 h-5 border-2 rounded-full border-white/30 border-t-white animate-spin" />
                        <span className="text-sm font-bold">Processing...</span>
                      </>
                    ) : !canGenerateHighlight() ? (
                      <>
                        <AlertCircle size={18} />
                        <div className="text-left">
                          <div className="text-sm font-bold">Not Available</div>
                          <div className="text-xs opacity-80">Match not live/finished</div>
                        </div>
                      </>
                    ) : (
                      <>
                        <Sparkles size={18} />
                        <div className="text-left">
                          <div className="text-sm font-bold">Generate Highlights</div>
                          <div className="text-xs opacity-80">120 seconds • Stream Source</div>
                        </div>
                      </>
                    )}
                  </button>
                </div>
                
                <div className="p-4 mt-6 border border-white/10 rounded-xl bg-black/30">
                  <div className="flex items-start gap-3">
                    <AlertCircle size={18} className="text-yellow-500 mt-0.5" />
                    <div>
                      <div className="mb-1 text-sm font-bold">How it works</div>
                      <p className="text-sm text-white/60">
                        Clicking "Generate Highlights" will call the Firebase function which processes the stream. 
                        The system uses the stream URL from the match to create highlights. 
                        Generated highlights are available for 72 hours.
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Right Column - Stats & Info */}
          <div className="space-y-8">
            {/* Match Info Card */}
            <div className="border border-white/10 rounded-[2rem] p-6 bg-gradient-to-br from-zinc-900/50 to-zinc-800/30">
              <div className="flex items-center gap-2 mb-6">
                <Shield size={20} className="text-red-500" />
                <h3 className="text-sm font-black tracking-wider uppercase">Match Information</h3>
              </div>
              
              <div className="space-y-4">
                <div className="flex justify-between pb-3 border-b border-white/10">
                  <span className="text-sm text-white/60">League</span>
                  <span className="font-bold">{league}</span>
                </div>
                
                <div className="flex justify-between pb-3 border-b border-white/10">
                  <span className="text-sm text-white/60">Status</span>
                  <div className="flex items-center gap-2">
                    <div className={`w-2 h-2 rounded-full ${matchData?.status === 'LIVE' ? 'bg-green-500 animate-pulse' : 'bg-red-500'}`}></div>
                    <span className="font-bold">{matchData?.status || 'Finished'}</span>
                  </div>
                </div>
                
                <div className="flex justify-between pb-3 border-b border-white/10">
                  <span className="text-sm text-white/60">Kickoff</span>
                  <span className="font-bold">
                    {matchData?.kickoff ? new Date(matchData.kickoff).toLocaleDateString() : 'Today'}
                  </span>
                </div>
                
                <div className="flex justify-between">
                  <span className="text-sm text-white/60">View Count</span>
                  <span className="font-bold">{matchData?.viewCount || 0}</span>
                </div>
              </div>
              
              <div className="pt-6 mt-6 border-t border-white/10">
                <div className="text-xs text-white/40">
                  Highlight source: <span className="font-bold text-white/60">{streamSource || 'Primary Stream'}</span>
                </div>
              </div>
            </div>

            {/* Quick Actions */}
            <div className="border border-white/10 rounded-[2rem] p-6 bg-gradient-to-br from-zinc-900/50 to-zinc-800/30">
              <h3 className="mb-4 text-sm font-black tracking-wider uppercase">Quick Actions</h3>
              
              <div className="space-y-3">
                <a
                  href={`/match/${id}`}
                  className="flex items-center gap-3 p-3 transition-all border border-white/10 rounded-xl bg-black/30 hover:bg-black/50 hover:border-red-600/30"
                >
                  <Video size={18} className="text-red-500" />
                  <div>
                    <div className="text-sm font-bold">Watch Full Match</div>
                    <div className="text-xs text-white/60">Return to live stream</div>
                  </div>
                </a>
                
                <button
                  onClick={() => {
                    const url = `https://www.youtube.com/results?search_query=${encodeURIComponent(`${homeTeam} vs ${awayTeam} highlights`)}`;
                    window.open(url, '_blank');
                  }}
                  className="flex items-center w-full gap-3 p-3 transition-all border border-white/10 rounded-xl bg-black/30 hover:bg-black/50 hover:border-red-600/30"
                >
                  <Play size={18} className="text-red-500" />
                  <div>
                    <div className="text-sm font-bold">YouTube Highlights</div>
                    <div className="text-xs text-white/60">Search on YouTube</div>
                  </div>
                </button>

                <button
                  onClick={() => {
                    const url = `https://us-central1-votexlive-3a8cb.cloudfunctions.net/getAvailableStreams?matchId=${id}`;
                    window.open(url, '_blank');
                  }}
                  className="flex items-center w-full gap-3 p-3 transition-all border border-white/10 rounded-xl bg-black/30 hover:bg-black/50 hover:border-red-600/30"
                >
                  <ExternalLink size={18} className="text-red-500" />
                  <div>
                    <div className="text-sm font-bold">API: Available Streams</div>
                    <div className="text-xs text-white/60">View raw stream data</div>
                  </div>
                </button>
              </div>
            </div>

            {/* Generated Highlight Info */}
            {highlight && (
              <div className="border border-white/10 rounded-[2rem] p-6 bg-gradient-to-br from-zinc-900/50 to-zinc-800/30">
                <div className="flex items-center gap-2 mb-4">
                  <Sparkles size={18} className="text-yellow-500" />
                  <h3 className="text-sm font-black tracking-wider uppercase">Highlight Information</h3>
                </div>
                
                <div className="space-y-3">
                  <div className="text-sm">
                    <span className="text-white/60">Quality:</span>
                    <span className="ml-2 font-bold">{highlight.quality || '720p'}</span>
                  </div>
                  
                  <div className="text-sm">
                    <span className="text-white/60">Duration:</span>
                    <span className="ml-2 font-bold">{highlight.duration || 120} seconds</span>
                  </div>
                  
                  <div className="text-sm">
                    <span className="text-white/60">Source:</span>
                    <span className="ml-2 font-bold">{highlight.streamServer || 'StreamEast'}</span>
                  </div>
                  
                  {highlight.generatedAt && (
                    <div className="text-sm">
                      <span className="text-white/60">Generated:</span>
                      <span className="ml-2 font-bold">
                        {new Date(highlight.generatedAt).toLocaleTimeString([], {hour: '2-digit', minute:'2-digit'})}
                      </span>
                    </div>
                  )}
                  
                  {highlight.expiresAt && (
                    <div className="text-sm">
                      <span className="text-white/60">Expires:</span>
                      <span className="ml-2 font-bold">
                        {new Date(highlight.expiresAt).toLocaleDateString()}
                      </span>
                    </div>
                  )}
                </div>
                
                {highlight.watchUrl && (
                  <button
                    onClick={() => window.open(highlight.watchUrl, '_blank')}
                    className="w-full px-4 py-3 mt-6 text-sm font-bold transition-all bg-gradient-to-r from-red-600 to-red-700 hover:from-red-700 hover:to-red-800 rounded-xl"
                  >
                    Watch Stream
                  </button>
                )}
              </div>
            )}
          </div>
        </div>

        {/* Footer Note */}
        <div className="p-4 mt-8 border border-white/5 rounded-xl bg-black/20">
          <p className="text-xs leading-relaxed text-center text-white/60">
            ⚡ <strong>Powered by Vortex Live AI</strong> • Highlights are generated from live streams • 
            Streams sourced from third-party providers • Quality varies by source • 
            <a href="https://vortexlive.online" className="mx-1 text-red-400 hover:underline">vortexlive.online</a>
          </p>
        </div>
      </div>
    </div>
  );
};

export default HighlightPage;